version: 2
jobs:
  build:
    docker:
      - image: docker:17-git
    steps:
      - checkout
      - run:
          name: check current branch
          command: git branch
      - setup_remote_docker
      - run:
          name: check docker
          command: ls -la /var/run/
      - run:
          name: docker build
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-latest -t ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8} .
      - run:
          name: run and test
          command: docker run --rm ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-latest ls -la /microservice
      - run:
          name: docker login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: push image to registry
          command: |
            docker push ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-latest
            docker push ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}
