version: 2
jobs:
  build:
    docker:
      - image: docker:17-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker build
          command: docker build --build-arg SSH_KEY="${GITHUB_KEY}" -t koyfin/ciq-finantials-provider:${CIRCLE_BRANCH}-latest -t koyfin/ciq-finantials-provider:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8} .
      - run:
          name: docker login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: push image to registry
          command: |
            docker push koyfin/ciq-finantials-provider:${CIRCLE_BRANCH}-latest
            docker push koyfin/ciq-finantials-provider:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}
  deploy-prod:
    docker:
      - image: docker:17-git
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b8:e5:6a:5f:3c:ca:6a:77:00:69:4a:f6:04:d5:c4:f7"
      - run: which ssh
      - run: ssh-add -l
      - run: ssh -o StrictHostKeyChecking=no -o ProxyCommand="ssh -A -o StrictHostKeyChecking=no -q -W %h:%p circleci@34.207.40.58" circleci@172.31.96.208 docker service ls

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: test2
      - deploy-prod:
          requires:
            - hold
