version: 2
jobs:
  build:
    docker:
      - image: docker:17-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker build
          command: docker build --build-arg SSH_KEY="${GITHUB_KEY}" -t koyfin/ciq-finantials-provider:${CIRCLE_BRANCH}-latest -t koyfin/ciq-finantials-provider:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8} .
      - run:
          name: docker login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: push image to registry
          command: |
            docker push koyfin/ciq-finantials-provider:${CIRCLE_BRANCH}-latest
            docker push koyfin/ciq-finantials-provider:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}
  deploy-prod:
    docker:
      - image: docker:17-git
    steps:
      - run: which ssh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: test
      - deploy-prod:
          requires:
            - hold
